### ISSUE TITLE
Is the plugin compatible with moodle 3.8

### ISSUE THREAD

**Issue by chryssis** [lucaboesch/moodle-quizaccess_safeexambrowser#10]
Hi, I was wondering whether the plugin is compatible with the new moodle version 3.8. 
We have installed it in our moodle installation, but when as a user I activated a quiz with that option, it asks me to download the plugin. In particular, I get the message:

You must use an approved version of Safe Exam Browser to attempt this quiz. You can download it from https://safeexambrowser.org/download_en.html#Moodle.

I have downloaded the SEB and I am using the one which the exam key got from the config file.

**Comment by lucaboesch** [comment]
Dear @chryssis in the Moodle plugins directory I see a whole bunch of sites using the safeexambrowser quit accessrule with version 3.8.
Since the basics of quiz accessrules haven't changed and I hear no complaints I assume this is working flawlessly.
Probably would be a good thing to release a version labeled as compatible to 3.8 anyway.

Best,
Luca
